// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hugageystrtrgxlucqst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Z2FnZXlzdHJ0cmd4bHVjcXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjM2NDIsImV4cCI6MjA3MjMzOTY0Mn0.8gPZ6et6F6PSmzVQlwJFuH_UAAtmAVbsWeHsVuHbtqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});